[package]
name = "nuc140-rust-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1

[build-dependencies]
cc = "1"
